#!/bin/bash

# 尝试使用未设置值的变量，脚本将停止执行
set -o nounset

config_file="$dbuilder_path/dbuilder.conf"
github_id=""
token=""

init_config()
{
    github_id=$(grep '^GITHUB_ID=' "$config_file" | cut -d '=' -f2)

    if [ -z "$github_id" ]; then
        echo "Github ID为，请输入数据: "
        read github_id
        sed -i 's|^GITHUB_ID=.*|GITHUB_ID='"${github_id}"'|' "$config_file"
    fi

    if [ -e "/tmp/github_token" ]; then
        token=$(cat "/tmp/github_token")
    else
        echo "Github Token为空，请输入数据: "
        read token
        echo "$token" >> /tmp/github_token
    fi
}

fork_repo()
{
    init_config
    url="https://api.github.com/repos/deepin-community/$2/forks"
    curl -X POST \
        -H "Authorization: token $token" \
        $url

}

diff_source()
{
    source dbuilder-source pre "${2}"

    repo_path="$psource_path/repo"
    source_path="$psource_path/${psource}"

    repo_url="git@github.com:$3/${psource}.git"
    # clone代码
    if [ ! -e "repo" ]; then
        git clone $repo_url $repo_path
    fi

    push_branch=$(cd $dbuilder_path && grep '^PUSH_BRANCH=' "$config_file" | cut -d '=' -f2)
    cd $repo_path
    # 如果分支不存在就创建
    if ! git branch | grep -q $push_branch; then
        git branch $push_branch
    fi
    git switch $push_branch

    cp -r $repo_path/.{git,github} $source_path
    cp -r $repo_path/debian/deepin $source_path/debian
}

diff_source_from_my_repo()
{
    init_config
    version=$(grep '^PACKAGE_VERSION=' "$config_file" | cut -d '=' -f2)
    if [ -z "$version" ]; then
        echo "发行版为空，请输入数据 (例: [ buster ] [ buster-backports ] [ bullseye ] [ bookworm ] [ sid ]): "
        read version
        sed -i 's|^PACKAGE_VERSION=.*|PACKAGE_VERSION='"${version}"'|' "$config_file"
    fi
    url="https://packages.debian.org/${version}/${2}"
	version_list=(bookworm bullseye buster)
	psource_exist=$(curl $url | grep "psource")
	if [ -z "$psource_exist" ]; then
		for version in "${version_list[@]}";
		do
			url="https://packages.debian.org/${version}/${2}"
			psource_exist=$(curl $url | grep "psource")
			[ ! -z "$psource_exist" ] && break
		done
	fi

    # 调用Python脚本并将结果逐行存储在数组中
    results=()
    while IFS= read -r result; do
        results+=("$result")
    done < <(python3 $dbuilder_path/crawler $url)

    psource="${results[0]}"

    fork_repo "" "$psource"

    diff_source "" "$2" "$github_id"
}


case "$1" in
    fork)
        fork_repo "$@"
        ;;
    diff)
        diff_source "$@"
        ;;
    diffm)
        diff_source_from_my_repo "$@"
        ;;
esac